### ISSUE TITLE
Issue with rate matcher

### ISSUE THREAD

**Issue by anitasusan** [robmaunder/turbo-3gpp-matlab#7]
Hi, I was trying to decode a LTE downlink signal using the turbo decoder and had few doubts regarding it. 
The rate matcher is expected the input stream to be in form of 3 X C format. But how do we convert an input bit stream into that format? is it sequentially divided or is there a specific format

**Comment by robmaunder** [comment]
Hello. The rate matching is described in Section 5.1.4.1 of 3GPP TS 36.212.
